### ISSUE TITLE
BS3 branch = Can't expand details 

### ISSUE THREAD

**Issue by olivierHa** [shinken-monitoring/mod-webui#129]
Hello, 

Using bs3 branch, expanding details doesn't work in alerts view, you can expand every host, but not a particular one.

Olivier

**Comment by mohierf** [comment]
I suppose that the concerned view is the Problems view, right ? 

 If so, I am currently refactoring this view because I also noticed some problems in its content ... I will commit some modifications soon about it.

**Comment by andyxning** [comment]
i meat that in our situation, too. One of our front end team worker said that it is the Javascript problem.

**Comment by lermit** [comment]
Hi,

I confirm that. I've Fix a similar mistake in a past pull request. If i've right it's related to host containing dot.

Regards

**Comment by mohierf** [comment]
@andyxning : is it possible that you copy an image of the javascript console ? I cannot reproduce the problem in my current configuration ...

**Comment by maethor** [comment]
I think we can close this bug since we have completely rewrite the /problems view.

**Comment by andyxning** [comment]
@maethor , you said that this problem has been resolved in bs-3 branch?

**Comment by maethor** [comment]
Yes, we have entirely rewritten the /problems view. Is it not fixed for you ?

**Comment by andyxning** [comment]
I just want to make sure of that.:)

I will give ti a try.

++++++
Ning Xie


2015-06-04 13:24 GMT+08:00 Guillaume Subiron <notifications@github.com>:
