### ISSUE TITLE
Unable to load WebUI2 logs pages

### ISSUE THREAD

**Issue by Dual-Boot** [shinken-monitoring/mod-webui#362]
Hello,

When I go to the following URL : http://localhost:7767/logs I get the following messages : 
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://localhost:7767/logs' caused an error:

Internal Server Error

Exception:

KeyError('max_records',)

Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 400, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/logs/views/logs.tpl", line 45, in <module>
    #    <a><i class="fa fa-gear"></i> Logs limit: {{params['max_records']}}</a>
KeyError: 'max_records'

```

So I have checked the code into the file named logs.tpl on line 45.
I seems that the block of code which is commented is in fact read as non commented code.
Here is the sample : 
```
  <!--
  <li class="sliding-element">
    <a><i class="fa fa-gear"></i> Logs limit: {{params['max_records']}}</a>
  </li>
  -->

```
 Is-it a bug from bottle.py or the syntax is wrong ?
If I delete this block of code I have an other error, but it seems to be link to an other problem.
For your information the next error is the following : 
```
Error: 500 Internal Server Error

Sorry, the requested URL 'http://shinken.freesquare.org:7767/logs' caused an error:

Internal Server Error

Exception:

TypeError("'NoneType' object is not iterable",)

Traceback:

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/var/lib/shinken/modules/webui2/module.py", line 400, in lock_version
    return f(**args)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3619, in wrapper
    return template(tpl_name, **tplvars)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3595, in template
    return TEMPLATES[tplid].render(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3399, in render
    self.execute(stdout, env)
  File "/usr/local/lib/python2.7/dist-packages/bottle.py", line 3386, in execute
    eval(self.co, env)
  File "/var/lib/shinken/modules/webui2/plugins/logs/views/logs.tpl", line 134, in <module>
    %for log in records:
TypeError: 'NoneType' object is not iterable

```
 This error looks like this bug #296

  Regards,

**Comment by mohierf** [comment]
I fixed your first error with a commit in the develop branch several days ago: https://github.com/shinken-monitoring/mod-webui/commit/93de44f144d69881345a00f53e38a8887c575ce5. Deleting the block of code is the solution ...

Concerning the second error, it occurs becausse you do not have any log records in your database ... probably because of a misconfiguration. Do you confirm you have installed the mongo-logs module for your broker ? What is its configuration ?

**Comment by Dual-Boot** [comment]
I missed your commit. So I will delete the code.
For the second error you are right I do not install the mongo-logs module.
So it seems that module is mandatory.

**Comment by Dual-Boot** [comment]
I did what is indicated here : https://github.com/shinken-monitoring/mod-webui/wiki/Installing-WebUI-logs-and-availability-modules
And add in the webui2.cfg : 
```
uri                        mongodb://localhost/?safe=false
database                  shinken

logs_collection            logs
hav_collection             availability

modules SQLitedb,mongo-logs
```
An I still have the same second error but now I have this message in the brokerd.log 
```
WARNING: [broker-master] [WebUI-logs] no get history external module defined!
```
Any idea ?
 Regards,

**Comment by Dual-Boot** [comment]
OK, first I remove mon-logs from modules into webui2.cfg and I installed mon-logs with shinken install.
But I still have the error.

**Comment by Dual-Boot** [comment]
OK OK, I pushed the module in the broker and now it works.
Thank you for helping.
